spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://ip:port/db
    username: your_username
    password: your_password
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1

mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

aliyun:
  oss:
    endpoint:
    bucket:
    accessKeyId:
    accessKeySecret: